version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: test_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: test_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
