version: '3.8'

services:
  postgres-prod:
    image: postgres:14
    container_name: test_postgres-prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5431"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis-prod:
    image: redis:7
    container_name: test_redis-prod
    restart: always
    ports:
      - "6371:6371"

volumes:
  pgdata:
